const POST_USERNAME = "POST_USERNAME";
const GET_CANCHAS = "GET_CANCHAS";
const GET_CANCHAS_DISPONIBLE = "GET_CANCHAS_DISPONIBLE";
const GET_RESERVA = "GET_RESERVA";
const DELETE_RESERVA = "DELETE_RESERVA";
const GET_TEAMS = "GET_TEAMS";
const GET_NOTIFICACIONES = "GET_NOTIFICACIONES";
const GET_TEAMS_ID = "GET_TEAMS_ID";
const GET_PLAYERS = "GET_PLAYERS";
const GET_NOTIFICACIONES_MY_TEAM = "GET_NOTIFICACIONES_MY_TEAM"

export {
  GET_PLAYERS,
  POST_USERNAME,
  GET_CANCHAS,
  GET_CANCHAS_DISPONIBLE,
  GET_RESERVA,
  DELETE_RESERVA,
  GET_TEAMS,
  GET_NOTIFICACIONES,
  GET_TEAMS_ID,
  GET_NOTIFICACIONES_MY_TEAM
};
